name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Import smoke test
        run: |
          python - <<'PY'
          import importlib
          for m in ["genetic_algorithm","pso_algorithm","instance_parser","genetic_matrix","pso_matrix","comparare"]:
              importlib.import_module(m)
          print("Imports OK")
          PY

      - name: Parser smoke test (ESC07.sop)
        continue-on-error: true
        run: |
          python - <<'PY'
          import os, sys
          from instance_parser import parse_sop_file
          p = os.path.join("sop_instances","ESC07.sop")
          if not os.path.exists(p):
              print("::warning ::Missing sop_instances/ESC07.sop — skipping")
              sys.exit(0)
          nodes, matrix, precedence = parse_sop_file(p)
          assert len(nodes) == len(matrix), "nodes/matrix size mismatch"
          print("Parser OK:", len(nodes), "nodes")
          PY
