name: build.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        env:
          MPLBACKEND: Agg  # headless matplotlib

      - name: Smoke test (imports + tiny parse)
        run: |
          python - <<'PY'
          import sys, pathlib
          import matplotlib, networkx
          print("OK imports:", matplotlib.__version__, networkx.__version__)
          p = pathlib.Path("sop_instances/ESC07.sop")
          if p.exists():
              from instance_parser import parse_sop_file
              nodes, M, prec = parse_sop_file(str(p))
              assert len(nodes) > 0 and len(M) > 0
              print("OK parser: nodes", len(nodes), "matrix", len(M), "x", len(M[0]), "prec", len(prec))
          else:
              print("NOTE: ESC07.sop absent in CI; skipped parser check")
          PY
        env:
          MPLBACKEND: Agg
